steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['endpoints', 'services', 'deploy', 'openapi-run.yaml', '--project', 'cloudhired']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['endpoints', 'configs', 'list', '--service', 'api.cloudhired.com']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['./gcloud_build_image.sh', '-s', 'api.cloudhired.com', '-c', 'does not matter', '-p', 'cloudhired']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['./deploy_run.sh']
