steps:
- name: 'ubuntu'
  args: ['ls', '-a']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['endpoints', 'services', 'list']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'print-access-token']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['./gcloud_build_image.sh', '-s', 'api.cloudhired.com', '-c', '2020-12-20r0', '-p', 'cloudhired']
- name: 'ubuntu'
  args:
    - -c
    - |
      # Read from "/workspace"
      echo "New image we saved " $(cat /workspace/new_image.txt) &&